name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
      # volume
      # env
      # ports    can be array
      # options: --cpu 1 --host
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release