name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node node-version
        run: node -v
      - uses: actions/step-node@v1
        with:
          node version: 6
      - name: Log node version
        run: node -v