name: Shell Commands  # Name of entire workflow

on: [push]      # Events that trigger workflow

jobs: # In a workflow you can have 1 or more jobs.
  run-shell-command:   # This job is called run-shell-command
    runs-on: ubuntu-latest  # Can use specific version or the latest (uses bash cmds)
    timeout-minutes: 5   #Time out in 5 minutes.
    steps:
      - name: echo a string       # Step Name
        run: echo "Hello World"   # run a shell command
        continue-on-error: true   # Runs all steps in the job. 
      - name: multiline script    # This step runs 2 commands.
        run: |
          node -v
          npm -v
      - name: python Command      # This step runs python
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:           # This job runs windows
    runs-on: windows-latest
    needs: ["run-shell-command"]   # We need to run-shell-command
    steps:
      - name: Directory PowerShell  # Step
        run: Get-Location
      - name: Directory Bash        # Step runs bash
        run: pwd
        shell: bash