name: Test Workflow

on: [push]
jobs:
  run-windows-commands:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
